added workflow updates

diff --git a/.github/workflows/packerBuild.yaml b/.github/workflows/packerBuild.yaml
--- a/.github/workflows/packerBuild.yaml
+++ b/.github/workflows/packerBuild.yaml
@@ -76,6 +76,10 @@ jobs:
           echo "Latest version: $LATEST"
           # Create a new launch template version
           LAUNCH_TEMPLATE_VERSION=$(aws ec2 create-launch-template-version --launch-template-name "$LAUNCH_TEMPLATE_NAME" --source-version "$LATEST" --launch-template-data "{\"ImageId\":\"${{ env.AMI_ID }}\"}" --query 'LaunchTemplateVersion.VersionNumber' --output text)
+          if [ -z "$LAUNCH_TEMPLATE_VERSION" ] || [ "$LAUNCH_TEMPLATE_VERSION" == "0" ]; then
+            echo "Failed to create launch template version"
+            exit 1
+          fi
           echo "Launch template version: $LAUNCH_TEMPLATE_VERSION"
 
       - name: Update Auto Scaling Group
@@ -89,6 +93,7 @@ jobs:
           # Start an instance refresh for the Auto Scaling group
           echo "Starting instance refresh for ASG"
           aws autoscaling start-instance-refresh --auto-scaling-group-name asg --strategy Rolling
+
 
 
 
